# Copyright (C) 2015-2016 Synopsys Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

# REPLACEME
# set srcdir "/home/user/arc_gnu/gcc/gcc/testsuite"
# set arc_exec_prefix "/home/user/arc_gnu/INSTALL/bin/arc-elf32"

set target_alias    "arc-elf32"
set target_triplet  "arc-default-elf32"
set rootme	    "."
# GCC dump-noaddr.x test passes to gcc options that cause it to create "dump"
# files in $tmpdir/dump{1,2}/ directories. GCC doesn't create directories
# itself, therefore dump-noaddr.x has to do that. But it does this in a wrong
# way - it omits the "tmpdir" and creates directories in $PWD. Consequently for
# this test to pass it is required that $tmpdir == $PWD.
set tmpdir	    "."
set CFLAGS	    ""
set CXXFLAGS	    ""
set SIM		    "${arc_exec_prefix}-run"
set GDB		    "${arc_exec_prefix}-gdb"
# Binutils
set NM		    "${arc_exec_prefix}-nm"
set SIZE	    "${arc_exec_prefix}-size"
set OBJDUMP	    "${arc_exec_prefix}-objdump"
set OBJCOPY	    "${arc_exec_prefix}-objcopy"
set AR		    "${arc_exec_prefix}-ar"
set STRIP	    "${arc_exec_prefix}-strip"
set READELF	    "${arc_exec_prefix}-readelf"
set ELFEDIT	    "${arc_exec_prefix}-elfedit"
# ld
set LD		    "${arc_exec_prefix}-ld"

set CC_FOR_TARGET   "${arc_exec_prefix}-gcc"
set CXX_FOR_TARGET  "${arc_exec_prefix}-g++"

if { $tool == "gcc" || $tool == "g++" } {
    set GCC_UNDER_TEST  "${arc_exec_prefix}-gcc"
    set GXX_UNDER_TEST  "${arc_exec_prefix}-g++"
} else {
    set CC		"${arc_exec_prefix}-gcc"
    set CXX		"${arc_exec_prefix}-g++"
}

switch $tool {
    libstdc++ {
	set baseline_subdir_switch "--print-multi-directory"
    }
    gdb {
	# By default GDB is called with -data-directory option. This wreaks
	# havoc when using an installed GDB, because pass data-directory value
	# is invalid. To fix the problem it is needed to override
	# INTERNAL_GDBFLAGS variable.
	set ::INTERNAL_GDBFLAGS "-nw -nx"
	source $srcdir/lib/append_gdb_boards_dir.exp
	if {[string match arc*-linux-uclibc $target_triplet]} {
	    set gdb_server_prog "/usr/bin/gdbserver"
	    # REPLACEME
	    # set toolchain_sysroot_dir "/home/user/arc_gnu/INSTALL/arc-snps-linux-uclibc/sysroot"
	}
    }
}
