#!/bin/sh

# Nasty Sphinx 1.4 uses some stuff that causes an error on my CentOS 6 host
# when building PDF (tex never works same on two machines). Has to use
# Sphinx 1.3.5 to avoid triggering an error.
if ! pip3 show Sphinx ; then
    # PIP will always download file at URL, hence it is required to explicitly
    # check if package has been already installed to avoid unnecessary
    # download.
    pip3 install --user \
	https://github.com/sphinx-doc/sphinx/archive/1.3.5.tar.gz
fi

pip3 install --user \
    pygments \
    sphinx_rtd_theme

make clean
make html
make latexpdf

