# Copyright (C) 2016 Synopsys, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


# This board specification is for use with the ARC OpenOCD.

search_and_load_file "library file" "arc-elf32-generic.exp" $boards_dir

# EM Starter Kit is presumed.
set_board_info arc,openocd_cfg "board/snps_em_sk_v2.2.cfg"
set_board_info arc,openocd_prog openocd
set_board_info arc,openocd_log_level 0

# Assume that this is a CCM design (should be evaluated dynamically, somehow).
set_board_info arc,has_executable_stack 0

# GDB test break-unload-file.exp does command "file", which resets gdbarch to
# ARCompact one, which doesn't play well with OpenOCD when actual target is ARC v2.
if { !([check_target_arc700] || [check_target_arc600] || [check_target_arc601]) } {
    set_board_info gdb_init_command "set arch ARCv2"
}

proc arc-openocd_reboot { cfg } {
    puts "Reboot is forbidden for this board - it means that test suite is "
    puts "broken and resuming doesn't make sense and is unlikely to yield "
    puts "sensible results."
    exit 1
}

arc_openocd_start

# vim: noexpandtab sts=4 ts=8:
