#!/bin/sh
/remote/nl20h2/claziss/work/qemu/install/bin/qemu-system-arc -M arc-sim \
   -m 2G -nographic -no-reboot -monitor none -serial stdio -kernel $1 | grep -q "0"
RET=$?

echo "*** EXIT code ${RET}"
